name: RandallBryant.com
favicon: null
layout_spectrum: 0.31467
typography_spectrum: 0.65818
title: RandallBryant.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fffdee'
    - '#7b7b7b'
    - '#79b9f8'
    - '#c8c2ac'
  brandStrength: 0.1875
  lightness: 0.4375
  saturation: 0.5625
  rhythmicContrast: 0.6251253308728337
purpose: []
